# Generated by Django 6.0.6 on 2026-06-17 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_aula', models.CharField(max_length=100)),
                ('capacidad_maxima', models.IntegerField()),
            ],
            options={
                'db_table': 'core_aula',
            },
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_carrera', models.CharField(max_length=255)),
                ('sigla_carrera', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'core_carrera',
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_docente', models.CharField(max_length=50, unique=True)),
                ('nombre_docente', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'core_docente',
            },
        ),
        migrations.CreateModel(
            name='GrupoMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_grupo', models.CharField(max_length=50)),
                ('gestion', models.CharField(max_length=20)),
                ('cupo_limite', models.IntegerField()),
                ('docente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrador.docente')),
            ],
            options={
                'db_table': 'core_grupomateria',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(max_length=20)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('aula', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrador.aula')),
                ('grupo_materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.grupomateria')),
            ],
            options={
                'db_table': 'core_horario',
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_materia', models.CharField(max_length=255)),
                ('sigla_materia', models.CharField(max_length=20, unique=True)),
                ('credito_materia', models.IntegerField()),
                ('periodo_materia', models.CharField(max_length=50)),
                ('ht', models.IntegerField(default=0)),
                ('hp', models.IntegerField(default=0)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.carrera')),
            ],
            options={
                'db_table': 'core_materia',
            },
        ),
        migrations.AddField(
            model_name='grupomateria',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.materia'),
        ),
        migrations.CreateModel(
            name='Prerrequisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerrequisitos', to='administrador.materia')),
                ('materia_requerida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='es_prerrequisito_de', to='administrador.materia')),
            ],
            options={
                'db_table': 'core_prerrequisito',
            },
        ),
    ]
