# Generated by Django 6.0.6 on 2026-06-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='es_electiva',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='materia',
            name='requisito_texto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='materia',
            name='credito_materia',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='materia',
            name='periodo_materia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
