# Generated by Django 6.0.6 on 2026-06-19 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_materia_es_electiva_materia_requisito_texto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='sigla_materia',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='materia',
            unique_together={('sigla_materia', 'carrera')},
        ),
    ]
