# Generated by Django 6.0.6 on 2026-06-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0003_alter_materia_sigla_materia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='tipo_materia',
            field=models.CharField(default='Normal', max_length=50),
        ),
    ]
