# Generated by Django 6.0.6 on 2026-06-26 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0004_materia_tipo_materia'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupomateria',
            name='color_hex',
            field=models.CharField(default='#3b82f6', max_length=7),
        ),
    ]
