# Generated by Django 6.0.6 on 2026-06-18 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_materia_es_electiva_materia_requisito_texto_and_more'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='aula',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='carrera',
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.carrera'),
        ),
        migrations.RemoveField(
            model_name='grupomateria',
            name='docente',
        ),
        migrations.RemoveField(
            model_name='grupomateria',
            name='materia',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='grupo_materia',
        ),
        migrations.RemoveField(
            model_name='historialacademico',
            name='grupo_materia',
        ),
        migrations.AlterField(
            model_name='detallesimulacion',
            name='grupo_materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.grupomateria'),
        ),
        migrations.RemoveField(
            model_name='prerrequisito',
            name='materia_requerida',
        ),
        migrations.RemoveField(
            model_name='prerrequisito',
            name='materia',
        ),
        migrations.AddField(
            model_name='historialacademico',
            name='materia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administrador.materia'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Aula',
        ),
        migrations.DeleteModel(
            name='Carrera',
        ),
        migrations.DeleteModel(
            name='Docente',
        ),
        migrations.DeleteModel(
            name='Horario',
        ),
        migrations.DeleteModel(
            name='GrupoMateria',
        ),
        migrations.DeleteModel(
            name='Materia',
        ),
        migrations.DeleteModel(
            name='Prerrequisito',
        ),
    ]
