# Generated by Django 6.0.6 on 2026-06-18 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_horario_aula_remove_materia_carrera_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('extracto', models.CharField(max_length=500)),
                ('contenido', models.TextField()),
                ('categoria', models.CharField(max_length=100)),
                ('color_categoria', models.CharField(max_length=50)),
                ('imagen_url', models.URLField(blank=True, max_length=500, null=True)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
