# Generated by Django 6.0.6 on 2026-06-26 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0004_materia_tipo_materia'),
        ('core', '0004_usuario_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(default='VA', max_length=50)),
                ('modalidad', models.CharField(default='PRESENCIAL', max_length=100)),
                ('horario', models.CharField(default='Lu 07:00-09:15 | Mi 09:15-11:30', max_length=255)),
                ('gestion', models.CharField(default='1-2026', max_length=20)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estudiante')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.materia')),
            ],
        ),
    ]
