# Generated by Django 6.0.6 on 2026-06-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_inscripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='imagen_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
